### ISSUE TITLE
Facing issue with dic_dict

### ISSUE THREAD

**Issue by manojbadhe** [yanghoonkim/question_generation#6]
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    tf.app.run(main)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 122, in main
    write_result(predict_results, FLAGS.dic_dir)
  File "main.py", line 23, in write_result
    with open(dic_dir) as dic:
IOError: [Errno 2] No such file or directory: ''

**Comment by jdxyw** [comment]
you need set DIC_DIR in run.sh

**Comment by yanghoonkim** [comment]
@manojbadhe is it solved?

**Comment by yanghoonkim** [comment]
I have solved the issue in current version
